version: "3"
services:
  express-app:
    build:
      context: ./express-app
      dockerfile: Dockerfile
    volumes:
      - ./express-app/uploads:/app/uploads
    ports:
      - "3001:3001"

  fe:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./express-app/uploads:/usr/share/nginx/html
    ports:
      - "89:80"
