version: "3"
services:
  express-app:
    build:
      context: ./express-app
      dockerfile: Dockerfile
    volumes:
      - ./express-app/uploads:/app/uploads
    ports:
      - "3001:3001"
    depends_on:
      - source-downloader

  share-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./express-app/uploads:/usr/share/nginx/html
    ports:
      - "89:80"
    depends_on:
      - source-downloader
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "88:80"
    depends_on:
      - source-downloader

  source-downloader:
    image: alpine/git
    volumes:
      - ./express-app:/app
    command: git clone https://github.com/ledainghia/imagestoragewithnodejs.git /app
